### ISSUE TITLE
gitignore/exposed userdata

### ISSUE THREAD

**Issue by MrtnBckr** [SteveTheSloth/Django-Budget-app#2]
Füge niemals Nutzerdaten einer Anwendung zum Repository hinzu. Du hast die sqlite Datei gerade mit drin. Füge stattdessen eine .gitignore Datei hinzu, die alle Dateien benennt, die nicht mit ins Repo sollen.

**Comment by MrtnBckr** [comment]
__pycache__ sollte auf jeden Fall auch mit in die gitignore und hat im Repo nichts verloren.

**Comment by SteveTheSloth** [comment]
Das verstehe ich natürlich, die sqlite Datei habe ich aber absichtlich mit drin gelassen, damit die Datenbankstruktur direkt einsehbar ist. Es ist ja keine ausgerollte Anwendung und die Nutzerdaten sind nur beispielhaft. Ist das Quatsch?

**Comment by MrtnBckr** [comment]
Ja, das ist eher unüblich. Die Datenbankstruktur lässt sich in Django ja anhand der models.py-Dateien sehen. Und in Produktiv-Umgebungen nutzt du auch nicht sqlite, sondern eine richtige DB wie postgres. 

Eventuell ergibt es Sinn, eine DB mit Beispieldaten vorzuhalten, dann aber in einem /example/-Ordner oder so, auf den in der Readme verwiesen wird.

**Comment by SteveTheSloth** [comment]
Ist jetzt in einer gitignore. Muss ich dann aber komplett neu pushen um es aus der repo zu entfernen, ne?
