### ISSUE TITLE
Exposed secrets

### ISSUE THREAD

**Issue by MrtnBckr** [SteveTheSloth/Django-Budget-app#3]
https://github.com/SteveTheSloth/Django-Budget-app/blob/f91287f96f42fc3463ce808b965ff418cce1996c/budget/budget/settings.py#L23

In einem Programmierbeispiel jetzt nicht sonderlich schlimm, aber trotzdem sollten die Secrets nicht im Repo landen. Eher lösen über Environment-Variablen oder lokaler (nicht eingecheckter) settings-files oder ähnlich.

**Comment by SteveTheSloth** [comment]
Danke. Genau wie bei der gitignore muss ich das erneut pushen, damit es tatsächlich nicht mehr drin ist, gel?

**Comment by MrtnBckr** [comment]
Ja, dieser Secret Key ist jetzt für alle Zeit in der Git Historie verankert. ^^
